### ISSUE TITLE
Fix README and repo

### ISSUE THREAD

**Issue by alokshandilya** [goswamiAnushka/Nestopia_draft#1]
- `npm install` in the README, yet you have `node_modules/` in the directly

**Comment by goswamiAnushka** [comment]
???

**Comment by goswamiAnushka** [comment]
Please be clear , did not get you .

**Comment by alokshandilya** [comment]
- learn about `.gitignore`
- do a quick google search to see what files you should add into `.gitignore` for the project's stack
- as of now, you can merge my pull request
